package com.rs.tmobiledemosample.data.remote

import com.rs.tmobiledemosample.core.util.Constants
import com.rs.tmobiledemosample.domain.model.StudentResponse
import retrofit2.http.GET

interface StudentApiService {

    @GET(Constants.URL_APPENDING_KEY) // Replace with the URL generated by Mocky
    suspend fun getStudents(): StudentResponse

}